#output directory
output_dir: 

# tsv file with an absolute file path per line
input_dir: 

# reference read files. Need to specify either this or reference_assembly.
reference_reads_R1: ""
reference_reads_R2: ""

# reference assembly. Need to specify either this or reference_reads_R1 and reference_reads_R2.
reference_assembly: ""

# shovel additional params e.g. --trim for read trimming
shovill_params: ""

# size of kmer used for ska2
ksize: 31

# path to snpEff config, found in script directory
snpEFF_config: scripts/snpEff.config

# path to bakta database, needs to be downloaded and updated before running (see here https://github.com/oschwengers/bakta#database-download)
bakta_db: 