#output directory
output_dir: 

# tsv file with an absolute file path per line
input_dir: 

# reference read files
reference_reads_R1: 
reference_reads_R2: 

# shovel additional params e.g. --trim for read trimming
shovill_params: ""

# size of kmer used for ska2
ksize: 21

snpEFF_config: scripts/snpEff.config