#output directory
output_dir: 

# tsv file with an absolute file path per line
input_dir: 

# reference read files
reference_reads_R1: 
reference_reads_R1: 

# path to directory containing non-reference reads
read_dir:

# size of kmer used for ska2
ksize: 21