# output directory
output_dir: 

# tsv file with an absolute file path per line
input_dir: 

# reference read files. Can specify if reference is in form of reads.
# can also specify as ancestral strain reads along with reference assembly, 
# if ancestral strain is different from the reference to be aligned to, to ignore SNPs present in ancestral strain.
reference_reads_R1: ""
reference_reads_R2: ""

# reference assembly. Need to specify either this or reference_reads_R1 and reference_reads_R2.
reference_assembly: ""

# reference Genbank file. Can specify this if wanting to use specific assembly with annotations.
reference_assembly_gbk: ""

# Aligner to use for variant calling. Should be one of "ska" (aligning closely-related sequences) or "bwa" (aligning distantly-related sequences)
alignment_method: ska

# shovel additional params e.g. --trim for read trimming
shovill_params: ""

# size of kmer used for ska2
ksize: 31

# path to snpEff config, found in script directory
snpEFF_config: scripts/snpEff.config

# path to bakta database, needs to be downloaded and updated before running (see here https://github.com/oschwengers/bakta#database-download)
bakta_db: 